// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Course is the predicate function for course builders.
type Course func(*sql.Selector)

// Exam is the predicate function for exam builders.
type Exam func(*sql.Selector)

// Student is the predicate function for student builders.
type Student func(*sql.Selector)
